// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7w5_kaLe89C6a7KOlvlZCdw5GXhMceME',
    appId: '1:287340004462:web:6ec4fdf13fb93b7ea1127f',
    messagingSenderId: '287340004462',
    projectId: 'laparapp-project-12939',
    authDomain: 'laparapp-project-12939.firebaseapp.com',
    storageBucket: 'laparapp-project-12939.firebasestorage.app',
    measurementId: 'G-E5VTF6NZ22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKP39Koj8YI1xqrWk_JrYGYKWGgvDTUQ',
    appId: '1:287340004462:android:11d81e8dfa1ce6d1a1127f',
    messagingSenderId: '287340004462',
    projectId: 'laparapp-project-12939',
    storageBucket: 'laparapp-project-12939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtPdfkwtyL2gFTP1PGVNbHU4S42fch5o',
    appId: '1:287340004462:ios:9cc5980eb1a3208ba1127f',
    messagingSenderId: '287340004462',
    projectId: 'laparapp-project-12939',
    storageBucket: 'laparapp-project-12939.firebasestorage.app',
    androidClientId: '287340004462-m9jdsr74e2pon9207mad2sjs2vu8qf63.apps.googleusercontent.com',
    iosClientId: '287340004462-oo05aacdo9prvko5mc75aqgv5j5sgqch.apps.googleusercontent.com',
    iosBundleId: 'com.example.laparApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQtPdfkwtyL2gFTP1PGVNbHU4S42fch5o',
    appId: '1:287340004462:ios:9cc5980eb1a3208ba1127f',
    messagingSenderId: '287340004462',
    projectId: 'laparapp-project-12939',
    storageBucket: 'laparapp-project-12939.firebasestorage.app',
    androidClientId: '287340004462-m9jdsr74e2pon9207mad2sjs2vu8qf63.apps.googleusercontent.com',
    iosClientId: '287340004462-oo05aacdo9prvko5mc75aqgv5j5sgqch.apps.googleusercontent.com',
    iosBundleId: 'com.example.laparApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7w5_kaLe89C6a7KOlvlZCdw5GXhMceME',
    appId: '1:287340004462:web:5e1cd2b7160d1e6fa1127f',
    messagingSenderId: '287340004462',
    projectId: 'laparapp-project-12939',
    authDomain: 'laparapp-project-12939.firebaseapp.com',
    storageBucket: 'laparapp-project-12939.firebasestorage.app',
    measurementId: 'G-9CWNHBFKCT',
  );
}
